# This is a basic workflow that is manually triggered

name: Build LaTeX document

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: xelatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: sample.tex
          compiler: xelatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: sample.tex
          compiler: bibtex
      - name: xelatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: sample.tex
          compiler: xelatex
          args: -interaction=nonstopmode -shell-escape
      - name: xelatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: sample.tex
          compiler: xelatex
          args: -interaction=nonstopmode -shell-escape
