# This is a basic workflow that is manually triggered

name: Build LaTeX document

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: HermitSun/latex-action@v3
        with:
          root_file: sample.tex
          latexmk_use_xelatex: true
          args: '-bibtex'
